# Generated by Django 4.2.11 on 2024-03-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfidf', '0002_word_tfidf_word_idf_f2df34_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['id']},
        ),
    ]
