# Generated by Django 4.2.11 on 2024-03-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfidf', '0003_alter_document_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word_Document',
            new_name='WordDocument',
        ),
    ]
