# Generated by Django 4.2.11 on 2024-03-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfidf', '0004_rename_word_document_worddocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='documents',
        ),
        migrations.AddField(
            model_name='document',
            name='words',
            field=models.ManyToManyField(through='tfidf.WordDocument', to='tfidf.word'),
        ),
    ]
