# Generated by Django 4.2.11 on 2024-03-30 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfidf', '0007_alter_document_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='processed',
        ),
    ]
