# Generated by Django 4.2.11 on 2024-03-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfidf', '0009_word_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddocument',
            name='word_tf',
            field=models.FloatField(default=0.0),
        ),
    ]
